config/routes.rb
Rails.application.routes.draw do

  get 'cars/prices' => 'home#csv'

  get 'download/:id' => 'home#download', as: :download

  root 'home#index'

end

app/models/price.rb
class Price < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
require 'open-uri'
class HomeController < ApplicationController
	# include PriceExtractor

	before_action :validate_url, only: [:csv]
	
  def index
  end

  def csv
  	begin
  	  random_str = get_random_hex
  		filename = params[:url].split('/').last+"_"+random_str 
	  	Delayed::Job.enqueue(PriceExtractor.new(params[:url], filename, random_str))
      price_file = Price.new(file_key: random_str)
      if price_file.save
	      flash[:success] = "Your file is being prepared! Relax."
				redirect_to download_path(random_str)
			else
				flash[:alert] = "Try again in few moments."
				redirect_to :back
			end
		rescue
			flash[:alert] = "Error in fetching results."
			redirect_to :back
		end
  end

  def download
  	price_file = Price.find_by_file_key(params[:id])
  	if price_file.present? && price_file.file_path.present?
	  	filename = price_file.file_path[53..price_file.file_path.length]
	  	data = open(price_file.file_path)
		  send_data data.read, :type => "text/plain", 
			                      :filename=>"#{filename}",
			                      :disposition => 'attachment'
    elsif price_file.present?
    	# flash['info'] = "It is being uploaded. Try in few minutes: https://yalladata.herokuapp.com/download/#{params[:id]}"
    	# redirect_to root_path
    else
    	flash[:alert] = "Invalid File Path."
    	redirect_to root_path
    end
end 

  private
  def get_random_hex
  	SecureRandom.hex(10).to_s
  end

  def validate_url
  	unless params[:url].present? && params[:url].include?('yallamotor.com') &&
  		     (params[:url].split(':')[0] == 'http' || params[:url].split(':')[0] == 'https')
  		flash[:alert] = "Invalid URL."
			redirect_to :back
		end
  end
end
		   

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/download.html.haml
%p
  We are fetching results. You may download in few minutes by 
  = link_to 'reloading', 'javascript:void(0);', class: 'page-reload'
  the page.

app/views/home/index.html.haml
.container
  = form_tag(cars_prices_path, class: 'form-extractor', method: 'GET') do
    %h2.form-extractor-heading.panel Online Data Extractor for Yallamotor
    = url_field_tag 'url', '', class: 'form-control panel', pattern: "http?://.+|https?://.+", placeholder: 'Paste URL here...', required: ''
    %button.btn.btn-lg.btn-primary.btn-block.form-submit{:type => "submit"} Get CSV

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Yalladata"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to 'Yalladata', root_path, class: 'navbar-brand'

    #page-loader.display-none
      %h3
        %i.fa.fa-circle-o-notch.fa-spin.fa-2x
      %h4
        = 'Fetching...'
    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield